Personnal progression
PremierLangage/premierlangage pull request #456
Opened 2021-01-20 16:42 UTC by nborie

J'en ai marre ! C'est codé avec mes pieds mais je passe mon temps à résoudre des problèmes de merde en html/css pour lesquels je suis incompétent. C'est très moche, très très moche même... C'est pas des éléments ion qui sont web responsive, ici c'est tout dégueulasse, il y a beaucoup d'erreur dans le code (comme le placement des mois dans le récap-timing à la github...).

La seule chose propre : il n'y a qu'une seule requête bdd Django et un seul parcours sur cette dernière... Tout est construit ensuite sur cette dernière. Il n'y a aussi aucune comparaison entre apprenant ou promotion, c'est juste des grandeurs bruts extraite des answers de l'utilisateur qui clique. 

Si quelqu'un veut finir et polisser le code ainsi que le css/html, go ! Ça me ravage le cerveau les rendus html. Je suis d'une lenteur immonde et je recode tout from scratch alors que je suis sur que les vrais savent faire des calendriers... J'ai lu 2 heures des ref pour tenter de faire des hover ou onmouseover mais je me casse les dents à chaque fois. C'est trop dur pour moi, un L1 qui a suivi prog web serait plus compétent. Travis et codefactor vont être des vrais sapins de noël...

![exemple_1](https://user-images.githubusercontent.com/6042616/105206316-84df5800-5b46-11eb-8233-088a5c434b12.png)

![example_2](https://user-images.githubusercontent.com/6042616/105206345-8f015680-5b46-11eb-8ad3-72f231ce0922.png)

2021-01-21 23:24 UTC, nborie commented
Ok, j'ai quand même commencé à passer un coup de balay, à factoriser du code...

C'est encore moche mais bien moins que le premier jet... Suite plus tard....
![rigole_pas](https://user-images.githubusercontent.com/6042616/105424689-1d113600-5c48-11eb-9aa8-a6e71e4ca0c8.png)

2021-01-23 12:44 UTC, nborie commented
Ok, c'est à peu prêt final pour un premier jet....

Il faudra absolument tester cette branche sur un PL avec des users qui ont beaucoup beaucoup de trace (style des profs membre de PLaTon depuis plusieurs année...). Il se peut que la requette soit trop lourde, je ne sais pas...

Cette pull request implémente :
* un tableau de progression personnel pour TOUS les utilisateurs
* Chaque utilisateurs peut voir son propre tableau
* Les profs ont un panneau supplémentaire pour accéder à la progression de leur élèves
*Les élèves ne peuvent voir que leur propre progression

![haut](https://user-images.githubusercontent.com/6042616/105578460-b0e61d80-5d80-11eb-972e-57d868b4eb69.png)

![milieu](https://user-images.githubusercontent.com/6042616/105578467-b6436800-5d80-11eb-8a15-15197309c789.png)

![bas](https://user-images.githubusercontent.com/6042616/105578473-bd6a7600-5d80-11eb-92c9-208b5b13829f.png)

Le penneau pour avoir les cours dont on est prof + la liste des élèves sur chacun de ces cours :

![prof](https://user-images.githubusercontent.com/6042616/105578493-e559d980-5d80-11eb-90c8-0ab55e4ee868.png)

Un vision prof sur la progression d'un élève = même vue en fait...

![student](https://user-images.githubusercontent.com/6042616/105578505-fdc9f400-5d80-11eb-9264-fd1a0a43bbbd.png)

2021-01-23 15:41 UTC, nimdanor requested changes
See changes in file, before merging

2021-01-23 15:44 UTC, nimdanor approved these changes

2021-01-27 11:24 UTC, nimdanor commented
@YohanRameau tu pourra nous faire un point sur les tests et le déploiement de cette branche ?

2021-02-09 13:59 UTC, Killian1B approved these changes

2021-02-09 14:30 UTC, merged